[package]
authors = ["Cameron Diver <cameron@0xcd.dev>"]
edition = "2018"
name = "parser_combinators"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
